services:
  app:
    build: .
    ports: 
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.cw6yjly.mongodb.net/${MONGO_DB_NAME}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
